[package]
name = "market_avg"
version = "0.1.0"
authors = ["me"]
edition = "2018"

[dependencies]
serde_json = "1.0"
tarkov = "0.1.1"
tokio = { version = "0.2", features = ["macros"] }
indicatif = "0.14"
ajson = "0.2"